### ISSUE TITLE
Cannot upload the file!

### ISSUE THREAD

**Issue by Thomas-Austria** [th33xitus/kiauh#250]
### Linux Distribution

**Operating System:** Raspberry Pi OS Lite (64-bit) 2022-09-22

**KIAUH:** v5.0.0-1 
**Moonraker:** Installed: 2 
**Mainsail:** Installed! 
**Klipper:** Installed: 2 

**mainsail.cfg**
[virtual_sdcard]
path: /home/pi/Ender3Pro_data/gcodes
on_error_gcode:
  CANCEL_PRINT

**printer.cfg**
[virtual_sdcard]
path: /home/pi/Ender3Pro_data/gcodes

### What happened

I can't upload or edit Gcode files or Printer.cfg

2022-10-23 12:13:44,515 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.100.7
2022-10-23 12:13:44,517 [app.py:log_request()] - 101 GET /websocket (192.168.100.7) [_TRUSTED_USER_] 3.93ms
2022-10-23 12:13:44,519 [websockets.py:open()] - Websocket Opened: ID: 547552341536, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36, Host Name: 192.168.100.211
2022-10-23 12:13:44,530 [file_manager.py:get_file_list()] - Updating File List <config>...
2022-10-23 12:13:44,540 [app.py:log_request()] - 101 GET /websocket (192.168.100.7) [_TRUSTED_USER_] 2.04ms
2022-10-23 12:13:44,540 [websockets.py:open()] - Websocket Opened: ID: 547552083152, Proxied: False, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36, Host Name: 192.168.100.211
2022-10-23 12:13:44,546 [websockets.py:_handle_identify()] - Websocket 547552083152 Client Identified - Name: mainsail, Version: 2.3.1, Type: web
2022-10-23 12:13:44,629 [websockets.py:build_error()] - JSON-RPC Request Error: -32601
Metadata not available for <>
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/websockets.py", line 253, in execute_method
    result = await callback(params)
  File "/home/pi/moonraker/moonraker/websockets.py", line 362, in func
    result = await callback(
  File "/home/pi/moonraker/moonraker/components/file_manager/file_manager.py", line 332, in _handle_metadata_request
    raise self.server.error(
utils.ServerError: Metadata not available for <>

### What did you expect to happen

The file should load onto the Raspberry pi

### How to reproduce

Upload & Print --> cannot upload the file!

**Comment by th33xitus** [comment]
This issue doesn't seem related to KIAUH.
