### ISSUE TITLE
Mooncord Integration

### ISSUE THREAD

**Issue by S1L3NTANG3L** [th33xitus/kiauh#282]
### Is your feature request related to a problem? Please describe

Installing Mooncord(https://github.com/eliteSchwein/mooncord) manually after every major update is a hassle would by nice if it could also be installed using your script

### Describe the solution you'd like

Just a extra option under install that allows you to install mooncord from within kiauh

### Describe alternatives you've considered

The telegram bot is good but discord is already on my computer

**Comment by Torsospeed** [comment]
hi help required
kindly 
╔═══════════════════════════════════════════════════════╗
║ ~~~~~~~~~~~~~~~~~~~~~ [ KIAUH ] ~~~~~~~~~~~~~~~~~~~~~ ║
║        Klipper Installation And Update Helper         ║
║ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ║
╚═══════════════════════════════════════════════════════╝
[ERROR] An unexpected error occured:
None
Traceback (most recent call last):
  File "/home/biqu/kiauh/kiauh/core/menus/base_menu.py", line 184, in run
    self.display_menu()
  File "/home/biqu/kiauh/kiauh/core/menus/base_menu.py", line 178, in display_menu
    self.print_menu()
  File "/home/biqu/kiauh/kiauh/core/menus/main_menu.py", line 127, in print_menu
    self._fetch_status()
  File "/home/biqu/kiauh/kiauh/core/menus/main_menu.py", line 92, in _fetch_status
    self._get_component_status("mr", get_moonraker_status)
  File "/home/biqu/kiauh/kiauh/core/menus/main_menu.py", line 100, in _get_component_status
    status_data: ComponentStatus = status_fn(*args)
  File "/home/biqu/kiauh/kiauh/components/moonraker/moonraker_utils.py", line 37, in get_moonraker_status
    return get_install_status(MOONRAKER_DIR, MOONRAKER_ENV_DIR, Moonraker)
  File "/home/biqu/kiauh/kiauh/utils/common.py", line 113, in get_install_status
    instances = len(get_instances(instance_type))
  File "/home/biqu/kiauh/kiauh/utils/instance_utils.py", line 36, in get_instances
    instance_list = [
  File "/home/biqu/kiauh/kiauh/utils/instance_utils.py", line 37, in <listcomp>
    instance_type(get_instance_suffix(name, service)) for service in service_list
  File "<string>", line 7, in __init__
  File "/home/biqu/kiauh/kiauh/components/moonraker/moonraker.py", line 63, in __post_init__
    self.port: int | None = self._get_port()
  File "/home/biqu/kiauh/kiauh/components/moonraker/moonraker.py", line 143, in _get_port
    scp.read_file(self.cfg_file)
  File "/home/biqu/kiauh/kiauh/core/submodules/simple_config_parser/src/simple_config_parser/simple_config_parser.py", line 133, in read_file
    self._parse_line(line)
  File "/home/biqu/kiauh/kiauh/core/submodules/simple_config_parser/src/simple_config_parser/simple_config_parser.py", line 98, in _parse_line
    self.config[self.current_section][option] = {"_raw": line, "value": value}
KeyError: None
