### ISSUE TITLE
moonraker error in fluidd and mainsail, missing libsodium23

### ISSUE THREAD

**Issue by Deefonzo** [th33xitus/kiauh#89]
After a fresh install on latest raspbian lite, fluidd and mainsail complained about an error in moonraker config, section "authorization". Syntax was good, the log said:

`2021-06-03 22:52:02,957 [moonraker.py:load_component()] - Unable to load component: (authorization)
Traceback (most recent call last):
  File "/home/pi/moonraker/moonraker/moonraker.py", line 196, in load_component
    module = importlib.import_module("components." + component_name)
  File "/home/pi/moonraker-env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/moonraker/moonraker/components/authorization.py", line 22, in <module>
    from libnacl.sign import Signer, Verifier
  File "/home/pi/moonraker-env/lib/python3.7/site-packages/libnacl/__init__.py", line 80, in <module>
    nacl = _get_nacl()
  File "/home/pi/moonraker-env/lib/python3.7/site-packages/libnacl/__init__.py", line 75, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.23, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4,`

Installing libsodium helped, maybe include that in install_moonraker.sh?

installed versions:
kiauh: v3.0.0-53
moonraker: v0.6.0-144
klipper: v0.9.1-533

Cheers,
Pete

**Comment by th33xitus** [comment]
Thank you! I updated the script.
